### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by dandyraka** [dandyraka/TeleBackup#2]
- [x] Stats, total file each folder
- [x] Leech. Gdrive / zippy
- [x] Multi download by url. (loop)
- [x] leech dood and more
